vich_uploader:
    db_driver: orm
    storage: file_system

    mappings:
        formation_images:
            uri_prefix: /images/formations
            upload_destination: "%kernel.project_dir%/public/images/formations"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
